package models

// UserProfileResponseModel is used when fetching the
// public profile information of a user, it returns
// stats and basic info about the user
// TODO: Put checkmark if the profile pic is an NFT
type UserProfileResponseModel struct {
	BaseResponseModel
	Info struct {
		Username      string      `json:"username"`
		UserGroups    interface{} `json:"userGroups"`
		JoinDate      string      `json:"joinDate"`
		Signature     string      `json:"signature"`
		PictureLink   string      `json:"pictureLink"`
		VerifiedMark  bool        `json:"verifiedMark"`
		WalletAddress string      `json:"walletAddress"`
	} `json:"info"`
	Stats struct {
		Posts          int64 `json:"posts"`
		Threads        int64 `json:"threads"`
		Reputation     int64 `json:"reputation"`
		MarketListings int64 `json:"marketListings"`
		Vouches        int64 `json:"vouches"`
	} `json:"stats"`
	Restrictions struct {
		Banned     bool   `json:"banned"`
		BanReason  string `json:"banReason"`
		BanExpiry  string `json:"banExpiry"`
		Muted      bool   `json:"muted"`
		MuteReason string `json:"muteReason"`
		MuteExpiry string `json:"muteExpiry"`
	} `json:"restrictions"`
	ContactInfo struct {
		DiscordID  string `json:"discordID"`
		DiscordTag string `json:"discordTag"`
		Telegram   string `json:"telegram"`
	} `json:"contactInfo"`
}

// UserCardInfo is sent with every thread or market
// listing and is generated by a function inside the database
// file that gets the info by the user ID
type UserCardInfo struct {
	Username     string `json:"username"`
	Signature    string `json:"signature"`
	VerifiedMark bool   `json:"verifiedMark"`
	PictureLink  string `json:"pictureLink"`
	Reputation   int64  `json:"reputation"`
	Vouches      int64  `json:"vouches"`
	JoinDate     string `json:"joinDate"`
}

// NewUserProfilePicture is used to update the user profile
// picture, it only allows imgur and imgbb
type NewUserProfilePicture struct {
	PictureLink string `json:"pictureLink"`
	UseNFT      bool   `json:"useNFT"`
	NFTAddress  string `json:"NFTAddress"`
}

// UpdateUserProfile is used to update certain data
// of the users profile
type UpdateUserProfile struct {
	Username   string `json:"username"`
	Signature  string `json:"signature"`
	DiscordId  string `json:"discordId"`
	DiscordTag string `json:"discordTag"`
	Telegram   string `json:"telegram"`
}
